version: "3"
services:
 prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"

 grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    user: "472"
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - "./datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml"
      - "./dashboard-provider.yml:/etc/grafana/provisioning/dashboards/dashboard-provider.yml"
      - "./dashboard.json:/var/lib/grafana/dashboards/dashboard.json"
    env_file:
      - monitoring.properties